// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloServices.proto

package com.pdist.tutorial;

public final class HelloServices {
  private HelloServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pdist_tutorial_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pdist_tutorial_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pdist_tutorial_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pdist_tutorial_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023HelloServices.proto\022\022com.pdist.tutoria" +
      "l\"3\n\014HelloRequest\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010" +
      "lastName\030\002 \001(\t\"!\n\rHelloResponse\022\020\n\010greet" +
      "ing\030\001 \001(\t2\\\n\014HelloService\022L\n\005hello\022 .com" +
      ".pdist.tutorial.HelloRequest\032!.com.pdist" +
      ".tutorial.HelloResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_pdist_tutorial_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_pdist_tutorial_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pdist_tutorial_HelloRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_com_pdist_tutorial_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_pdist_tutorial_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pdist_tutorial_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
